version: "3.7"

services:
    laravel:
        image: daxter1987/laravel:1.0.6
        container_name: finance-bot
        ports:
            - "8095:80"
        volumes:
            - .:/var/www/html
    db:
        image: mysql:5.7
        container_name: finance-bot_db
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "3398:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: local
            MYSQL_PASSWORD: local
